version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: atom_drops_db
    restart: always
    environment:
      POSTGRES_USER: shawn            # <--- Change this
      POSTGRES_PASSWORD: rootshawn123 # <--- Change this
      POSTGRES_DB: atom_drops
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: